// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSRXQuCsqZOroa1Yr9kEf2k4KXDazY0Jw',
    appId: '1:1033131122028:web:44d4d8bcf1e1e8c40f2749',
    messagingSenderId: '1033131122028',
    projectId: 'gaming-city-94354',
    authDomain: 'gaming-city-94354.firebaseapp.com',
    storageBucket: 'gaming-city-94354.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDlE0vCvB-ZARCp21wblgeYPtiqPRanSU',
    appId: '1:1033131122028:android:8c59eb30f90389bf0f2749',
    messagingSenderId: '1033131122028',
    projectId: 'gaming-city-94354',
    storageBucket: 'gaming-city-94354.firebasestorage.app',
    databaseURL: 'https://gaming-city-94354-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArcgypZ6od6UNCbEIxV1YYak9FqEw2Fmg',
    appId: '1:1033131122028:ios:0df865d640de06320f2749',
    messagingSenderId: '1033131122028',
    projectId: 'gaming-city-94354',
    storageBucket: 'gaming-city-94354.firebasestorage.app',
    iosBundleId: 'com.gamingcityapp.gaming2190',
    databaseURL: 'https://gaming-city-94354-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArcgypZ6od6UNCbEIxV1YYak9FqEw2Fmg',
    appId: '1:1033131122028:ios:4ed4fba93f313f120f2749',
    messagingSenderId: '1033131122028',
    projectId: 'gaming-city-94354',
    storageBucket: 'gaming-city-94354.firebasestorage.app',
    iosBundleId: 'com.example.gameCityApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSRXQuCsqZOroa1Yr9kEf2k4KXDazY0Jw',
    appId: '1:1033131122028:web:44d4d8bcf1e1e8c40f2749',
    messagingSenderId: '1033131122028',
    projectId: 'gaming-city-94354',
    authDomain: 'gaming-city-94354.firebaseapp.com',
    databaseURL:
        'https://gaming-city-94354-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gaming-city-94354.firebasestorage.app',
    measurementId: 'G-EGXF290KDW',
  );
}
